distributionName: javascript-cdk-demo
initDeployConfig:
  template: deployment-plan.yaml
  stackName: ${environment}-${distributionName}-deployment-plan

package:
  prePackage:
    commands:
      - attini configure set-dist-id --random
      - npm install
      - cdk synth --app "npx ts-node --prefer-ts-exts deployment-plan/deployment-plan.ts" > deployment-plan.yaml

