distributionName: javascript-cdk-demo
initDeployConfig:
  template: deployment-plan.yaml
  stackName: ${environment}-${distributionName}-deployment-plan

package:
  prePackage:
    commands:
      - attini configure set-dist-id --random
      - npm install
      - cdk synth  --app "node deployment-plan/deployment-plan.js" > deployment-plan.yaml
