distributionName: java-cdk-demo
initDeployConfig:
  template: deployment-plan-app/templateDir/DeploymentPlan.template.json
  stackName: ${environment}-${distributionName}-deployment-plan

package:
  prePackage:
    commands:
      - attini configure set-dist-id --random
      - cd deployment-plan-app
      - cdk synth --output templateDir --path-metadata false
