distributionName: java-cdk-demo
initDeployConfig:
  template: templateDir/DeploymentPlanStack.template.json
  stackName: ${environment}-${distributionName}-deployment-plan

package:
  prePackage:
    commands:
      - attini configure set-dist-id --random
      - cdk synth --output templateDir --path-metadata false --app "mvn -e -q compile -P deployment-plan exec:java"
