distributionName: python-cdk-demo
initDeployConfig:
  template: deployment-plan.yaml
  stackName: ${environment}-${distributionName}-deployment-plan

package:
  prePackage:
    commands:
      - attini configure set-dist-id --random

      - export PYTHONPATH="${PYTHONPATH}:$(pwd)"
      - cdk synth --app "python3 deployment_plan/deployment_plan.py" > deployment-plan.yaml